### ISSUE TITLE
Bug in Events List

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1069]
### Bug Report    

**Actual Behaviour**

When Event List is opened then a blank screen is displayed and on refreshing the following log is generated but the screen remains blank.

**Expected Behaviour**

State here what the feature should enable the user to do.

**Steps to reproduce it**

**LogCat for the issue**

`E/Logger: An exception occurred : Comparison method violates its general contract!
          java.lang.IllegalArgumentException: Comparison method violates its general contract!
              at java.util.TimSort.mergeLo(TimSort.java:773)
              at java.util.TimSort.mergeAt(TimSort.java:510)
              at java.util.TimSort.mergeCollapse(TimSort.java:437)
              at java.util.TimSort.sort(TimSort.java:241)
              at java.util.Arrays.sort(Arrays.java:1523)
              at java.util.Collections.sort(Collections.java:238)
              at io.reactivex.internal.functions.Functions$ListSorter.apply(Functions.java:505)
              at io.reactivex.internal.functions.Functions$ListSorter.apply(Functions.java:496)
              at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
              at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:113)
              at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onComplete(ObservableDoOnEach.java:143)
              at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onComplete(ObservableDoOnEach.java:143)
              at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onComplete(ObservableDoOnEach.java:143)
              at io.reactivex.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onComplete(ObservableDoFinally.java:93)
              at io.reactivex.internal.observers.DisposableLambdaObserver.onComplete(DisposableLambdaObserver.java:73)
              at io.reactivex.internal.observers.DisposableLambdaObserver.onComplete(DisposableLambdaObserver.java:73)
              at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
              at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:192)
              at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
              at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
              at android.os.Handler.handleCallback(Handler.java:751)
              at android.os.Handler.dispatchMessage(Handler.java:95)
              at android.os.Looper.loop(Looper.java:154)
              at android.app.ActivityThread.main(ActivityThread.java:6123)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Android version and Phone Model**

Add the Android version and the phone model on which the issue was encountered.
    
**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@sridharjajoo @mishuvs You guys can take this up if you want to. I'm busy with other issues right now.

**Comment by mishuvs** [comment]
Yes, unable to reproduce.
