### ISSUE TITLE
App Crash in Dashboard

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1131]
### Bug Report    

**Actual Behaviour**

When a newly created event is selected in event list layout then the dashboard loads and the app crashes with following error log.

**Expected Behaviour**

App must not crash.

**Steps to reproduce it**

Create a new event. Select it in dashboard.

**LogCat for the issue**

`E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-2
                  Process: org.fossasia.eventyay, PID: 5096
                  io.reactivex.exceptions.OnErrorNotImplementedException: FOREIGN KEY constraint failed (code 787)
                      at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:51)
                      at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onError(CompletableConcatArray.java:60)
                      at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onError(CompletablePeek.java:96)
                      at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:38)
                      at io.reactivex.Completable.subscribe(Completable.java:1794)
                      at io.reactivex.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
                      at io.reactivex.Completable.subscribe(Completable.java:1794)
                      at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:89)
                      at io.reactivex.internal.operators.completable.CompletableConcatArray.subscribeActual(CompletableConcatArray.java:33)
                      at io.reactivex.Completable.subscribe(Completable.java:1794)
                      at io.reactivex.Completable.subscribe(Completable.java:1782)
                      at org.fossasia.openevent.app.data.attendee.AttendeeRepositoryImpl.lambda$null$2$AttendeeRepositoryImpl(AttendeeRepositoryImpl.java:62)
                      at org.fossasia.openevent.app.data.attendee.AttendeeRepositoryImpl$$Lambda$7.accept(Unknown Source)
                      at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onNext(ObservableDoOnEach.java:95)
                      at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:51)
                      at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
                      at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:43)
                      at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
                      at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
                      at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at io.reactivex.internal.operators.observable.ObservableFlattenIterable.subscribeActual(ObservableFlattenIterable.java:44)
                      at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:39)
                      at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
                      at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at io.reactivex.internal.operators.observable.ObservableSwitchIfEmpty$SwitchIfEmptyObserver.onComplete(ObservableSwitchIfEmpty.java:70)
                      at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onComplete(ObservableDoOnEach.java:143)
                      at io.reactivex.internal.operators.single.SingleFlatMapIterableObservable$FlatMapIterableObserver.onSuccess(SingleFlatMapIterableObservable.java:99)
                      at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:56)
                      at io.reactivex.Single.subscribe(Single.java:3096)
                      at io.reactivex.internal.operators.single.SingleFlatMapIterableObservable.subscribeActual(SingleFlatMapIterableObservable.java:47)
                      at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:39)
                      at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
                      at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:39)
E/AndroidRuntime:     at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at io.reactivex.internal.operators.observable.ObservableSwitchIfEmpty.subscribeActual(ObservableSwitchIfEmpty.java:31)
                      at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at io.reactivex.internal.operators.observable.ObservableToListSingle.subscribeActual(ObservableToListSingle.java:58)
                      at io.reactivex.Single.subscribe(Single.java:3096)
                      at io.reactivex.internal.operators.single.SingleFlatMapIterableObservable.subscribeActual(SingleFlatMapIterableObservable.java:47)
                      at io.reactivex.Observable.subscribe(Observable.java:11442)
                      at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                      at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
                      at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                      at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)
                   Caused by: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
                      at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                      at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                      at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                      at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                      at com.raizlabs.android.dbflow.structure.database.AndroidDatabaseStatement.executeInsert(AndroidDatabaseStatement.java:83)
                      at com.raizlabs.android.dbflow.sql.saveable.ModelSaver.insert(ModelSaver.java:114)
                      at com.raizlabs.android.dbflow.sql.saveable.ListModelSaver.insertAll(ListModelSaver.java:55)
                      at com.raizlabs.android.dbflow.structure.ModelAdapter.insertAll(ModelAdapter.java:220)
                      at com.raizlabs.android.dbflow.structure.database.transaction.FastStoreModelTransaction$2.processModel(FastStoreModelTransaction.java:36)
                      at com.raizlabs.android.dbflow.structure.database.transaction.FastStoreModelTransaction.execute(FastStoreModelTransaction.java:88)
                      at com.raizlabs.android.dbflow.config.DatabaseDefinition.executeTransaction(DatabaseDefinition.java:283)
                      at org.fossasia.openevent.app.data.db.DbFlowDatabaseRepository.lambda$saveList$4$DbFlowDatabaseRepository(DbFlowDatabaseRepository.java:62)
                      at org.fossasia.openevent.app.data.db.DbFlowDatabaseRepository$$Lambda$4.run(Unknown Source)
                      at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)`

**Screenshots of the issue**
![crash](https://user-images.githubusercontent.com/23634977/41895585-0cfff6a4-7940-11e8-8e26-150d4b906264.gif)

**Android version and Phone Model**

Jelly Bean and Moto G4 Plus
    
**Would you like to work on the issue?**

Yes

**Comment by ShridharGoel** [comment]
Closed since it's not reproducible now.
