### ISSUE TITLE
App crashing on creating events

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1154]
### Bug Report    

**Actual Behaviour**
There are some weird errors taking place on event creation.
1) Multiple items of same event are getting created.
2) App is crashing when more events are getting added.

**Steps to reproduce it**
Create new events. (make sure latest commits are there)

**LogCat for the issue**
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{f3e1c04 position=0 id=-1, oldPos=4, pLpos:4 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{988868b VFED..... .F....ID 0,0-1080,1692 #7f09009c app:id/eventRecyclerView}, adapter:org.fossasia.openevent.app.core.event.list.EventsListAdapter@2a1d368, layout:android.support.v7.widget.LinearLayoutManager@7c0e381, context:org.fossasia.openevent.app.core.main.MainActivity@f205021
        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5610)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5792)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3763)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3527)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1191)
        at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:876)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:895)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
        at android.view.View.layout(View.java:16669)
        at android.view.ViewGroup.layout(ViewGroup.java:5440)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
    	at android.view.View.layout(View.java
```
**Screenshots of the issue**

**Android version and Phone Model**
Andorid 6.0.1 , API 23 , Redmi Note 3

**Would you like to work on the issue?**
Yes

**Comment by sridharjajoo** [comment]
@mishuvs @Masquerade0097 @srv-twry Are you encountering this kind of error?

**Comment by Masquerade0097** [comment]
@sridharjajoo No, I'm able to create new events successfully.

**Comment by sridharjajoo** [comment]
try creating a new account and try again
