### ISSUE TITLE
IllegalArgumentException: Unsupported ISO 3166 country

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#1156]
### Bug Report    

**Actual Behaviour**

Multiple exceptions are thrown on opening create event activity similar to following.
 `IllegalArgumentException: Unsupported ISO 3166 country`

**Steps to reproduce it**
Click on create event FAB.

**LogCat for the issue**

`D/CurrencyUtils: java.lang.IllegalArgumentException: Unsupported ISO 3166 country: es
                     at java.util.Currency.getInstance(Currency.java:140)
                     at org.fossasia.openevent.app.utils.CurrencyUtils.getCountryCurrencyMap(CurrencyUtils.java:75)
                     at org.fossasia.openevent.app.core.event.create.CreateEventPresenter.<init>(CreateEventPresenter.java:56)
                     at org.fossasia.openevent.app.core.event.create.CreateEventPresenter_Factory.get(CreateEventPresenter_Factory.java:29)
                     at org.fossasia.openevent.app.core.event.create.CreateEventPresenter_Factory.get(CreateEventPresenter_Factory.java:10)
                     at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                     at org.fossasia.openevent.app.common.mvp.view.BaseFragment.getPresenter(BaseFragment.java:31)
                     at org.fossasia.openevent.app.core.event.create.CreateEventFragment.onStart(CreateEventFragment.java:150)
                     at android.support.v4.app.Fragment.performStart(Fragment.java:2369)
                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
                     at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
                     at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3210)
                     at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:206)
                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:605)
                     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1270)
                     at android.app.Activity.performStart(Activity.java:6689)
                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2622)
                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
                     at android.os.Handler.dispatchMessage(Handler.java:102)
                     at android.os.Looper.loop(Looper.java:154)
                     at android.app.ActivityThread.main(ActivityThread.java:6123)
                     at java.lang.reflect.Method.invoke(Native Method)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Android version and Phone Model**

Nougat and Moto G4 Plus

**Comment by HHimanshusahni** [comment]
Can I work on this issue?

**Comment by Masquerade0097** [comment]
Yes

**Comment by HHimanshusahni** [comment]
@Masquerade0097 Please review the pull request.
