### ISSUE TITLE
App crashing on selecting events

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1170]
### Bug Report    

**Actual Behaviour**
1. When a new event is created and the event is selected the app is crashing. 
2. The events list is leaking a lot of memory as well.
3. When an item from an events list is long pressed the app is crashing.

This is happened after the latest commit.

**Expected Behaviour**
Shouldn't crash.

**Steps to reproduce it**
Create an event and select it.

**LogCat for the issue***

```
java.lang.NullPointerException: Attempt to read from field 'org.fossasia.openevent.app.data.event.EventAnalyticsDelegate org.fossasia.openevent.app.data.event.Event.analytics' on a null object reference
        at org.fossasia.openevent.app.core.event.dashboard.analyser.TicketAnalyser.analyseSoldTickets(TicketAnalyser.java:52)
        at org.fossasia.openevent.app.core.event.list.sales.SalesSummaryPresenter.lambda$loadDetails$1$SalesSummaryPresenter(SalesSummaryPresenter.java:61)
        at org.fossasia.openevent.app.core.event.list.sales.SalesSummaryPresenter$$Lambda$1.accept(Unknown Source)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:113)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onComplete(ObservableDoOnEach.java:143)
        at io.reactivex.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onComplete(ObservableDoFinally.java:93)
        at io.reactivex.internal.observers.DisposableLambdaObserver.onComplete(DisposableLambdaObserver.java:73)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(ObservableFlatMap.java:367)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(ObservableFlatMap.java:323)
        at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onComplete(ObservableFlatMap.java:300)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onComplete(ObservableDoOnEach.java:143)
        at io.reactivex.internal.observers.DisposableLambdaObserver.onComplete(DisposableLambdaObserver.java:73)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
        at io.reactivex.int
```

**Android version and Phone Model**
Android Marshmallow 6.0.1 and Redmi Note 3

**Comment by Masquerade0097** [comment]
@iamareebjamal @sridharjajoo Should we revert back the latest commit ?

**Comment by mishuvs** [comment]
The app is crashing when the call `eventRepository.getEvent(getId(), forceReload)` is made. The eventId() is not null. I tried checking out the previous commit before the ViewPager PR and found the same error.
I think it is because of the Rate Limiter.

**Comment by srv-twry** [comment]
> I think it is because of the Rate Limiter.

I don't think so but in order to verify this, please revert back to the commit before the rate limiter and check.

**Comment by mishuvs** [comment]
@srv-twry I tried checking out commits before the RateLimiter and couldn't reproduce this crash. It is crashing for the last 4 commits. Please try and confirm.

**Comment by srv-twry** [comment]
It is because of the rate limiter. Let me fix it. @Masquerade0097 I'll fix in a couple of hours. If I can't then you can revert that PR.
