### ISSUE TITLE
App crashing on selecting add location

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#1236]
### Bug Report    

**Actual Behaviour**
When the dialog box appears to enter the location details for publishing an event and the add location is selected, the app crashes.

**Steps to reproduce it**
In any event without location details, try to publish it and select add location.

**Android version and Phone Model**
Android 6.0.1 and Redmi Note 3

**Logcat**
```
 android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:682)
        at android.app.ContextImpl.startActivity(ContextImpl.java:669)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:341)
        at org.fossasia.openevent.app.core.event.dashboard.EventDashboardFragment.openEditEvent(EventDashboardFragment.java:204)
        at org.fossasia.openevent.app.core.event.dashboard.EventDashboardFragment$$Lambda$2.run(Unknown Source)
        at org.fossasia.openevent.app.ui.ViewUtils.lambda$showDialog$0$ViewUtils(ViewUtils.java:107)
        at org.fossasia.openevent.app.ui.ViewUtils$$Lambda$0.onClick(Unknown Source)
        at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
        at android.os.Handler.dispatchMessage(Handler.java:102)
```
**Would you like to work on the issue?**
Yes

**Comment by Masquerade0097** [comment]
@sridharjajoo Please post the logcat.

**Comment by sridharjajoo** [comment]
@Masquerade0097 I have updated the logcat
