### ISSUE TITLE
App crashes on swipe refresh in dashboard

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-orga-app#1674]
**Logs**
```
W/System.err: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.ArrayIndexOutOfBoundsException: length=24; index=1480000000
W/System.err:     at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
W/System.err:     at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:56)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
        at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
        at io.reactivex.internal.operators.completable.CompletableFromSingle$CompletableFromSingleObserver.onSuccess(CompletableFromSingle.java:51)
        at io.reactivex.internal.operators.single.SingleDoAfterSuccess$DoAfterObserver.onSuccess(SingleDoAfterSuccess.java:69)
        at io.reactivex.internal.operators.observable.ObservableToListSingle$ToListObserver.onComplete(ObservableToListSingle.java:111)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach$DoOnEachObserver.onComplete(ObservableDoOnEach.java:141)
```

**Smartphone Info:**

|               | |
|---------------|-|
|Android Version|Nougat 7.1.1|

**Would you like to work on the issue?**

- [ ] Yes
- [x] No
- Other:

**Comment by ShridharGoel** [comment]
Proper logs:
```
java.lang.ArrayIndexOutOfBoundsException: length=24; index=1480000000
        at com.eventyay.organizer.core.event.dashboard.analyser.ChartAnalyser$MyAxisValueFormatter.getFormattedValue(ChartAnalyser.java:296)
        at com.github.mikephil.charting.components.AxisBase.getFormattedLabel(AxisBase.java:472)
        at com.github.mikephil.charting.components.AxisBase.getLongestLabel(AxisBase.java:458)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeSize(XAxisRenderer.java:79)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxisValues(XAxisRenderer.java:74)
        at com.github.mikephil.charting.renderer.XAxisRenderer.computeAxis(XAxisRenderer.java:67)
        at com.github.mikephil.charting.charts.BarLineChartBase.notifyDataSetChanged(BarLineChartBase.java:332)
        at com.github.mikephil.charting.charts.Chart.setData(Chart.java:304)
        at com.eventyay.organizer.core.event.dashboard.analyser.ChartAnalyser.showChart(ChartAnalyser.java:264)
        at com.eventyay.organizer.core.event.dashboard.EventDashboardPresenter.loadCheckInTimesChart(EventDashboardPresenter.java:175)
        at com.eventyay.organizer.core.event.dashboard.EventDashboardPresenter.loadDetails(EventDashboardPresenter.java:75)
        at com.eventyay.organizer.core.event.dashboard.EventDashboardFragment.lambda$setupRefreshListener$1$EventDashboardFragment(EventDashboardFragment.java:136)
        at com.eventyay.organizer.core.event.dashboard.-$$Lambda$EventDashboardFragment$NIkC8b6RkjYXFUwU6z0bBdruCPo.onRefresh(lambda)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout$1.onAnimationEnd(SwipeRefreshLayout.java:195)
        at androidx.swiperefreshlayout.widget.CircleImageView.onAnimationEnd(CircleImageView.java:107)
        at android.view.ViewGroup.finishAnimatingView(ViewGroup.java:6239)
        at android.view.View.draw(View.java:17155)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.draw(View.java:17214)
        at android.view.View.updateDisplayListIfDirty(View.java:16193)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1256)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.draw(View.java:17214)
        at android.view.View.updateDisplayListIfDirty(View.java:16193)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.updateDisplayListIfDirty(View.java:16188)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1256)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.updateDisplayListIfDirty(View.java:16188)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1426)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.draw(View.java:17214)
        at android.view.View.updateDisplayListIfDirty(View.java:16193)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.updateDisplayListIfDirty(View.java:16188)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
        at android.view.View.updateDisplayListIfDirty(View.java:16188)
        at android.view.View.draw(View.java:16977)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3515)
```
