### ISSUE TITLE
App crashing on attendee click

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#298]
On attendees page, app crashes on attendee click. 

Error log:
```
java.lang.NullPointerException: 
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                                                at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1035)
                                                                                at java.text.DateFormat.parse(DateFormat.java:569)
                                                                                at org.fossasia.openevent.app.utils.DateUtils.getDate(DateUtils.java:103)
                                                                                at org.fossasia.openevent.app.utils.DateUtils.getDate(DateUtils.java:121)
                                                                                at org.fossasia.openevent.app.utils.DateUtils.formatDate(DateUtils.java:127)
                                                                                at org.fossasia.openevent.app.utils.DateUtils.formatDateWithDefault(DateUtils.java:135)
                                                                                at org.fossasia.openevent.app.utils.DateUtils.formatDateWithDefault(DateUtils.java:149)
                                                                                at org.fossasia.openevent.app.databinding.BottomsheetAttendeeCheckInBinding.executeBindings(BottomsheetAttendeeCheckInBinding.java:231)
```

**Comment by mejariamol** [comment]
@iamareebjamal Are you getting same error too?

**Comment by iamareebjamal** [comment]
No, log the date on which you are getting the error

**Comment by mejariamol** [comment]
I am getting today too. try using login mejariamol@gmail.com 12345678

**Comment by iamareebjamal** [comment]
I meant this is a date error, print the log of date string which is giving error
