### ISSUE TITLE
App crashing on Attendee click

### ISSUE THREAD

**Issue by mejariamol** [fossasia/open-event-orga-app#327]
On attendees page, app crashes on attendee click

The error log:
```org.fossasia.openevent.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.fossasia.openevent.app, PID: 4273
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1035)
        at java.text.DateFormat.parse(DateFormat.java:569)
        at org.fossasia.openevent.app.utils.DateUtils.getDate(DateUtils.java:103)
        at org.fossasia.openevent.app.utils.DateUtils.getDate(DateUtils.java:121)
        at org.fossasia.openevent.app.utils.DateUtils.formatDate(DateUtils.java:127)
        at org.fossasia.openevent.app.utils.DateUtils.formatDateWithDefault(DateUtils.java:135)
        at org.fossasia.openevent.app.utils.DateUtils.formatDateWithDefault(DateUtils.java:149)
        at org.fossasia.openevent.app.databinding.BottomsheetAttendeeCheckInBinding.executeBindings(BottomsheetAttendeeCheckInBinding.java:231)
        at android.databinding.ViewDataBinding.executeBindingsInternal(ViewDataBinding.java:379)
        at android.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:351)
        at android.databinding.ViewDataBinding$6.run(ViewDataBinding.java:178)
        at android.databinding.ViewDataBinding$5.onViewAttachedToWindow(ViewDataBinding.java:146)
        at android.view.View.dispatchAttachedToWindow(View.java:13584)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2831)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2838)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2838)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2838)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2838)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2838)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2838)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2838)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2838)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1510)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1251)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6438)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:795)
        at android.view.Choreographer.doCallbacks(Choreographer.java:598)
        at android.view.Choreographer.doFrame(Choreographer.java:567)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:781)
        at android.os.Handler.handleCallback(Handler.java:810)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:189)
        at android.app.ActivityThread.main(ActivityThread.java:5530)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
```

**Comment by iamareebjamal** [comment]
This is a really strange error. I think the easiest thing would be to add a null check in DateUtils

**Comment by mejariamol** [comment]
this returning null attendee. You may take a look
```
attendeeRepository.getAttendee(getId(), false)
            .compose(dispose(getDisposable()))
            .compose(result(getView()))
            .subscribe(attendee -> this.attendee = attendee, Logger::logError);
```

**Comment by iamareebjamal** [comment]
RxJava's subscribe method never emits a null value. This is their very strict policy, so it is not possible. It is possible that the attendee is getting bound to layout before setAttendee is called
