### ISSUE TITLE
bug: App crash in Ticket Create Layout

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#627]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
 
**Actual Behaviour**

The app crashes on entering the following values of ticket price in Ticket Create Layout - 
1. The entered value starts with a decimel.
2. The value is set to null.

**Expected Behaviour**

Crash shouldn't be there.

**Steps to reproduce it**

1. Set the price to null.
2. Enter a decimel.

**LogCat for the issue**

1.  `E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.fossasia.eventyay, PID: 2023
                  java.lang.NumberFormatException: For input string: "."
                      at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1306)
                      at java.lang.Float.parseFloat(Float.java:459)
                      at org.fossasia.openevent.app.common.app.binding.BindingAdapters.strToFloat(BindingAdapters.java:54)
                      at org.fossasia.openevent.app.databinding.TicketCreateFormBinding$4.onChange(TicketCreateFormBinding.java:154)
                      at android.databinding.adapters.TextViewBindingAdapter$1.onTextChanged(TextViewBindingAdapter.java:367)
                      at android.widget.TextView.sendOnTextChanged(TextView.java:8226)
                      at android.widget.TextView.handleTextChanged(TextView.java:8288)
                      at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10410)
                      at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1214)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
                      at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:844)
                      at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:198)
                      at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
                      at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:345)
                      at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:91)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6123)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

2.  `E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.fossasia.eventyay, PID: 2709
                  java.lang.NumberFormatException: empty String
                      at java.lang.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1071)
                      at java.lang.Float.parseFloat(Float.java:459)
                      at org.fossasia.openevent.app.common.app.binding.BindingAdapters.strToFloat(BindingAdapters.java:54)
                      at org.fossasia.openevent.app.databinding.TicketCreateFormBinding$4.onChange(TicketCreateFormBinding.java:154)
                      at android.databinding.adapters.TextViewBindingAdapter$1.onTextChanged(TextViewBindingAdapter.java:367)
                      at android.widget.TextView.sendOnTextChanged(TextView.java:8226)
                      at android.widget.TextView.handleTextChanged(TextView.java:8288)
                      at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10410)
                      at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1214)
                      at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
                      at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
                      at android.text.method.BaseKeyListener.backspaceOrForwardDelete(BaseKeyListener.java:346)
                      at android.text.method.BaseKeyListener.backspace(BaseKeyListener.java:68)
                      at android.text.method.BaseKeyListener.onKeyDown(BaseKeyListener.java:455)
                      at android.text.method.NumberKeyListener.onKeyDown(NumberKeyListener.java:138)
                      at android.widget.TextView.doKeyDown(TextView.java:6312)
                      at android.widget.TextView.onKeyDown(TextView.java:6102)
                      at android.view.KeyEvent.dispatch(KeyEvent.java:2684)
                      at android.view.View.dispatchKeyEvent(View.java:9879)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.support.v4.widget.NestedScrollView.dispatchKeyEvent(NestedScrollView.java:547)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1667)
                      at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:403)
                      at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1800)
                      at android.app.Dialog.dispatchKeyEvent(Dialog.java:757)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
                      at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
                      at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:317)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4339)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4310)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4007)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4064)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3914)
E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3880)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3888)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3861)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6257)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6196)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6157)
                      at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3659)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6123)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Android version and Phone Model**

Moto G4 Plus
    
**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
#626

**Comment by AkshayCHD** [comment]
@Masquerade0097 Sir, can i please work on this issue as i am already working on a very similar one.

**Comment by Masquerade0097** [comment]
@AkshayCHD Ya, please go on.
