### ISSUE TITLE
Providing runtime validation for fields in create copyright form

### ISSUE THREAD

**Issue by Masquerade0097** [fossasia/open-event-orga-app#712]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    

**Actual Behaviour**

When any incorrect url is entered in the url field and the form is submitted the server gives `HTTP 422 UNPROCESSABLE ENTITY`.

**Expected Behaviour**

There should be runtime validation of text input fields so that user can get feedback for incorrect input before submitting the form.

**Steps to reproduce it**

Enter incorrect url or year and then submite the form.

**LogCat for the issue**

`E/Logger: An exception occurred : HTTP 422 UNPROCESSABLE ENTITY
          retrofit2.adapter.rxjava2.HttpException: HTTP 422 UNPROCESSABLE ENTITY
              at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
              at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
              at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:43)
              at io.reactivex.Observable.subscribe(Observable.java:11442)
              at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
              at io.reactivex.Observable.subscribe(Observable.java:11442)
              at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
              at io.reactivex.Observable.subscribe(Observable.java:11442)
              at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
              at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
              at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
              at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
              at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
              at java.lang.Thread.run(Thread.java:761)`

**Android version and Phone Model**

Moto G4 Plus
   

**Would you like to work on the issue?**

Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal I implemented the runtime verification for fields but due to variable size of Base Bottom Sheet Dialog, when there is an error in textInputFields while typing the size of textInputLyout increases to show the error message which causes the increase in size of baseBottomSheetDialog and creates bad UX. Can I make it a proper fragment?

**Comment by iamareebjamal** [comment]
Yes, please make it a fragment

**Comment by sridharjajoo** [comment]
@Masquerade0097 Are you working in this ?
