### ISSUE TITLE
bug: App Crashing on start

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#831]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

App crashes on start

**LogCat for the issue**
```
03-24 23:33:01.418 25965-25965/org.fossasia.eventyay E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: org.fossasia.eventyay, PID: 25965
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fossasia.eventyay/org.fossasia.openevent.app.module.auth.AuthActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void org.fossasia.openevent.app.module.auth.login.contract.ILoginPresenter.attach(java.lang.Object)' on a null object reference
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2449)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509)
                                                                           at android.app.ActivityThread.access$1000(ActivityThread.java:153)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5523)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.fossasia.openevent.app.module.auth.login.contract.ILoginPresenter.attach(java.lang.Object)' on a null object reference
                                                                           at org.fossasia.openevent.app.module.auth.login.LoginFragment.onStart(LoginFragment.java:64)
                                                                           at android.support.v4.app.Fragment.performStart(Fragment.java:2369)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3210)
                                                                           at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:206)
                                                                           at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:605)
                                                                           at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                           at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
                                                                           at android.app.Activity.performStart(Activity.java:6320)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2412)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2509) 
                                                                           at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5523) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
03-24 23:33:01.419 25965-25965/org.fossasia.eventyay E/MQSEventManagerDelegate: failed to get MQSService.
03-24 23:33:01.425 1277-1291/? E/ActivityManager: Invalid thumbnail dimensions: 0x0
03-24 23:33:01.434 394-394/? E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8937.so
03-24 23:33:01.454 3719-3727/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [4, 0]
03-24 23:33:01.471 1991-2687/? E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8937.so
03-24 23:33:01.513 394-394/? E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8937.so
```

**Comment by srv-twry** [comment]
Please attach error log.
