### ISSUE TITLE
Cannot sign up and the issue with Android code.

### ISSUE THREAD

**Issue by Pancham97** [fossasia/open-event-orga-app#832]
**Is it a ?**

- [x] Bug Report

- [ ] Feature Request
    
- [ ] Chore
    
### Bug Report    

**Actual Behaviour**

1. When I sign up in the app, it shows "500 internal server error".
2. The Android Source Code shows "NullPointerException" on execution in AVD / device.

**Expected Behaviour**

1. Fix the server side issue and notify the user if he/she is successfully signed up. 
2. The expected output of the Android App is to at least open.

**LogCat for the issue**

```
03-24 07:26:15.130 3564-3564/org.fossasia.eventyay E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.fossasia.eventyay, PID: 3564
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fossasia.eventyay/org.fossasia.openevent.app.module.auth.AuthActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void org.fossasia.openevent.app.module.auth.login.contract.ILoginPresenter.attach(java.lang.Object)' on a null object reference
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                         at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                         at android.os.Looper.loop(Looper.java:164)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void org.fossasia.openevent.app.module.auth.login.contract.ILoginPresenter.attach(java.lang.Object)' on a null object reference
                                                                         at org.fossasia.openevent.app.module.auth.login.LoginFragment.onStart(LoginFragment.java:64)
                                                                         at android.support.v4.app.Fragment.performStart(Fragment.java:2369)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1752)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1821)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3251)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3210)
                                                                         at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:206)
                                                                         at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:605)
                                                                         at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
                                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1333)
                                                                         at android.app.Activity.performStart(Activity.java:6992)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2780)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                                                                         at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                         at android.os.Looper.loop(Looper.java:164) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6541) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Screenshots of the issue**

**## 1. Issue with sign up**

![image](https://user-images.githubusercontent.com/10232900/37867733-7adb74ea-2fc2-11e8-9ac2-cbef22bb5597.png)

**## 2. Issue with running the source code directly from Android Studio**
![image](https://user-images.githubusercontent.com/10232900/37867747-93fec332-2fc2-11e8-8875-bc7ea8259f1f.png)

**Android version and Phone Model**

Phone: Mi A1 (Android O v8.0.0)

**Description**

Let's start with fixing the initial issue of the Android Source Code not running as expected, then fix the server error, then focus on the optimization features!

**Would you like to work on the issue?**
I'd love to be a part of this community. I am ready to give all of my resources to get this thing working properly.

**Comment by iamareebjamal** [comment]
The issue with NPE is already open @Pancham97 at #831

**Comment by iamareebjamal** [comment]
And about sign up, you are using old API URL

**Comment by Pancham97** [comment]
I am using the link that is provided in the `open-event-orga-app` homepage. If that is using an old API, whose fault is it?

**Comment by iamareebjamal** [comment]
You are not using the development branch version of the app
