### ISSUE TITLE
Create tests for the LoginViewModel class

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/open-event-orga-app#983]
### Chore

**Description**
Write tests for the LoginViewModel class.

**Would you like to work on the issue?**
Yes

**Comment by sridharjajoo** [comment]
@iamareebjamal For the following test: 

   public void shouldNotLoginAutomatically( )  {
   
     Mockito.when(authModel.isLoggedIn()).thenReturn(false);
   
     loginViewModel.getLoginStatus().observeForever(observer);
   
     verify(observer).onChanged(false);
   
 }

I am getting an error:

Wanted but not invoked:
observer.onChanged(false);
-> at org.fossasia.openevent.app.core.presenter.LoginViewModelTest.shouldNotLoginAutomatically(LoginViewModelTest.java:80)
Actually, there were zero interactions with this mock.

Wanted but not invoked:
observer.onChanged(false);
-> at org.fossasia.openevent.app.core.presenter.LoginViewModelTest.shouldNotLoginAutomatically(LoginViewModelTest.java:80)
Actually, there were zero interactions with this mock.

**Comment by iamareebjamal** [comment]
https://pbochenski.pl/blog/07-12-2017-testing_livedata.html

**Comment by sridharjajoo** [comment]
On invoking login method of the LoginViewmodel class from test class, there is a null pointer exception pointing to the following code:
 public void login() {

        compositeDisposable.add(loginModel.login(login)
            .compose(disposeCompletable(compositeDisposable))
            .doOnSubscribe(disposable -> progress.setValue(true))
            .doFinally(() -> progress.setValue(false))
            .subscribe(() -> isLoggedIn.setValue(true),
                throwable -> error.setValue(ErrorUtils.getMessage(throwable))));
    }
Any possible ways to eliminate that?

**Comment by iamareebjamal** [comment]
Check what's null, paste the stack trace

**Comment by sridharjajoo** [comment]
java.lang.NullPointerException
	at org.fossasia.openevent.app.core.auth.login.LoginViewModel.login(LoginViewModel.java:47)	
at 
org.fossasia.openevent.app.core.viewmodel.LoginViewModelTest.shouldShowLoginError(LoginViewModelTest.java:82)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.mockito.internal.junit.JUnitRule$1.evaluateSafely(JUnitRule.java:63)
	at org.mockito.internal.junit.JUnitRule$1.evaluate(JUnitRule.java:43)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
`

**Comment by iamareebjamal** [comment]
What's at line 47

**Comment by sridharjajoo** [comment]
The 47th line as mentioned in above stack trace points to the .compose(disposableCompletable(compositeDisposable).

**Comment by iamareebjamal** [comment]
Add a break point and run in debug mode, it'll tell you which object is null

**Comment by sridharjajoo** [comment]
Yeah did it. Failing after this 
![screenshot from 2018-05-28 18-06-36](https://user-images.githubusercontent.com/20684618/40614841-06db2834-62a2-11e8-8347-d94d5a5617a1.png)

**Comment by iamareebjamal** [comment]
You don't need dispose completable in viewmodel

Remove this line

**Comment by sridharjajoo** [comment]
still getting the NPE and now on the next line

**Comment by iamareebjamal** [comment]
That means it was not on that line. Step into the code until you find what's null

**Comment by iamareebjamal** [comment]
From the looks of it, it's simply because you haven't initialized progress
